/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReviewsRouteImport } from './routes/_app/reviews'
import { Route as AppRankingsRouteImport } from './routes/_app/rankings'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppCitationsRouteImport } from './routes/_app/citations'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppRankingsKeywordIdRouteImport } from './routes/_app/rankings.$keywordId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppCitationsRoute = AppCitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRankingsKeywordIdRoute = AppRankingsKeywordIdRouteImport.update({
  id: '/$keywordId',
  path: '/$keywordId',
  getParentRoute: () => AppRankingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/citations': typeof AppCitationsRoute
  '/locations': typeof AppLocationsRoute
  '/rankings': typeof AppRankingsRouteWithChildren
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/rankings/$keywordId': typeof AppRankingsKeywordIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/citations': typeof AppCitationsRoute
  '/locations': typeof AppLocationsRoute
  '/rankings': typeof AppRankingsRouteWithChildren
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/rankings/$keywordId': typeof AppRankingsKeywordIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_app/citations': typeof AppCitationsRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/rankings': typeof AppRankingsRouteWithChildren
  '/_app/reviews': typeof AppReviewsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/rankings/$keywordId': typeof AppRankingsKeywordIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/citations'
    | '/locations'
    | '/rankings'
    | '/reviews'
    | '/settings'
    | '/rankings/$keywordId'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/citations'
    | '/locations'
    | '/rankings'
    | '/reviews'
    | '/settings'
    | '/'
    | '/rankings/$keywordId'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/login'
    | '/_app/citations'
    | '/_app/locations'
    | '/_app/rankings'
    | '/_app/reviews'
    | '/_app/settings'
    | '/_app/'
    | '/_app/rankings/$keywordId'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reviews': {
      id: '/_app/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rankings': {
      id: '/_app/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/citations': {
      id: '/_app/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof AppCitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rankings/$keywordId': {
      id: '/_app/rankings/$keywordId'
      path: '/$keywordId'
      fullPath: '/rankings/$keywordId'
      preLoaderRoute: typeof AppRankingsKeywordIdRouteImport
      parentRoute: typeof AppRankingsRoute
    }
  }
}

interface AppRankingsRouteChildren {
  AppRankingsKeywordIdRoute: typeof AppRankingsKeywordIdRoute
}

const AppRankingsRouteChildren: AppRankingsRouteChildren = {
  AppRankingsKeywordIdRoute: AppRankingsKeywordIdRoute,
}

const AppRankingsRouteWithChildren = AppRankingsRoute._addFileChildren(
  AppRankingsRouteChildren,
)

interface AppRouteChildren {
  AppCitationsRoute: typeof AppCitationsRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppRankingsRoute: typeof AppRankingsRouteWithChildren
  AppReviewsRoute: typeof AppReviewsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCitationsRoute: AppCitationsRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppRankingsRoute: AppRankingsRouteWithChildren,
  AppReviewsRoute: AppReviewsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
